### PR TITLE
Fix barcelona deploys failing sometimes

### LINKED ISSUE #650: Fix occasional deploy failures
Since #639 we have started loading up templates for deployments via S3. However, S3 is not immediately consistent, and so there can be a time after uploading when the file is not available for read. This manifests itself as an error like [this one](https://app.datadoghq.com/logs?cols=core_host%2Ccore_service&from_ts=1611882600000&index=&live=false&messageDisplay=inline&query=service%3Abarcelona2-worker&stream_sort=desc&to_ts=1611882900000&event=AQAAAXdLtNgY-MERAgAAAABBWGRMdE5wU0FBQlBRVzMtVkZaVXJRQUE). This phenomenon is [well known](https://stackoverflow.com/questions/8856316/amazon-s3-how-to-deal-with-the-delay-from-upload-to-object-availability). We can probably add a delay or retry to ensure that deploys don't just die for this reason.

### PR DESCRIPTION
**Pull request by davidsiaw**
~This PR introduces a wait after put object as a way to ensure that S3 has updated and made the object we just placed available.~

Turns out it was a method that should have been memoized but was not.

Fixes #650 

# How to test
This is one of those bugs that happens only occasionally due S3's behavior so this is difficult to reproduce. The normal path however, should not be any different.

1. Deploy an application
2. Check that it successfully deployed

### CODE REVIEW

**Comment by degicat** [comment]
@essa please review this

File: spec/lib/cloud_formation/executor_spec.rb [hunk 1]
```diff
@@ -11,16 +11,29 @@
...
 
     it "updates the stack directly if false" do
       expect(s3).to receive(:put_object)
+      expect(s3).to receive(:wait_until).with(:object_exists, anything, anything)
       expect(client).to_not receive(:create_change_set)
       expect(client).to receive(:update_stack)
       executor.update(change_set: false)
     end
+
+    it "creates a change set if true" do
```
Comment (essa) [inline spec/lib/cloud_formation/executor_spec.rb:28]: You forgot to change the comment?

**Review by essa — APPROVED** [review]
LGTM 👍 besides my comment

File: spec/lib/cloud_formation/executor_spec.rb (hunk 1 above)
Comment (davidsiaw) [reply spec/lib/cloud_formation/executor_spec.rb:28]: oops. Will fix this.

**Comment by davidsiaw** [comment]
@essa Sorry I'm making you review this twice.

I did some deeper testing to make sure I really fixed the issue, I made it so my stack was deployed in other regions but activate CF here so I can make sure the delay is very long, but it turns out it didn't matter where I deployed it!

I introduced a delay to see if that compensated and it caused it to fail even more often. I was so puzzled yesterday I was dreaming about the problem.

It turns out I have a function to provide `template_name` but it changes every second! This was why it works sometimes and fails sometimes. If the processing was not fast enough (within the second) then the template name will change, and CF will be given the wrong name, and thus S3 will say Access Denied because it is not the owner of the bucket.

Was a very stupid bug.

**Comment by essa** [comment]
Sorry, I missed it too.
I should have noticed on the first review.

File: lib/cloud_formation/executor.rb [hunk 2]
```diff
@@ -52,25 +52,42 @@ def create_change_set(type: "UPDATE")
...
 
     def stack_options
       upload_to_s3!
       {
         stack_name: stack.name,
         capabilities: ["CAPABILITY_IAM"],
-        template_url: "https://#{@bucket}.s3.amazonaws.com/#{template_name}"
+        template_url: "https://s3.#{stack.region}.amazonaws.com/#{@bucket}/#{template_name}"
       }
     end
```
Comment (essa) [inline lib/cloud_formation/executor.rb:92]: @davidsiaw 
How about making `template_name` local variable instead of an instance_method?
```ruby
def stack_options
  template_name = "stack_templates/#{stack.name}/#{Time.current.strftime("%Y-%m-%d-%H%M%S")}.template"
  upload_to_s3!(template_name)
  {
        stack_name: stack.name,
        capabilities: ["CAPABILITY_IAM"],
        template_url: "https://s3.#{stack.region}.amazonaws.com/#{@bucket}/#{template_name}"
  }
end
```

I think this makes more clear about the role or scope of the `template_name`.

- It will be used only for communication between uploading and executing
- We don't have to expose it to other classes or save it for future use

Comment (davidsiaw) [reply lib/cloud_formation/executor.rb:92]: Its used in two places. if I do that the code will be duplicated.

Comment (davidsiaw) [reply lib/cloud_formation/executor.rb:92]: @essa Its used in two places. if I do that the code will be duplicated.

Comment (essa) [reply lib/cloud_formation/executor.rb:92]: @davidsiaw 
I meant removing the method and making it a local variable for passing as a parameter.
Where is the duplication?

Comment (davidsiaw) [reply lib/cloud_formation/executor.rb:92]: @essa my bad, I misread your code. That is a good idea. will do that.
